### DISCUSSION TITLE
DietPi-Software | Cloudflared

### DISCUSSION THREAD

**Discussion by peejmio** [MichaIng/DietPi#5352] [Software Request]
- Software title | Cloudflared (Formerly Argo Tunnel)
- Short description | creates an encrypted tunnel between your origin web server and Cloudflare’s nearest data center, all without opening any public inbound ports. // exposes local servers behind NATs and firewalls to the public internet over Cloudflare network
- Official URL  | https://www.cloudflare.com/products/tunnel/
- GitHub URL  | https://github.com/cloudflare/cloudflared
- Official install documentation | https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/

#### Are there similar/alternative software titles available with DietPi-Software?
No

#### What makes your requested software better than the above solutions, if available?
<!- It is fully open source, without any limitation to free users. Free alternative to paid ngrok -->
- ...

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?

- ...

#### Can you provide the installation steps that you would suggest DietPi-Software to do?
1. Install cloudflared
2. Point your domain to cloudflare nameserver
3. authenticate cloudflared
4. configure config.yml with ingress settings to point to your apps specific port with hostname,
5. intall cloudflared as service

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.
Yes, I could help out with this if I have extra time but I'm not that expert in coding

**Comment by peejmio** [comment]
sample config

```
tunnel: --------------------------------
credential-file: /root/.cloudflared/--------------------------.json
no-autoupdate: true
ingress:
  - hostname: your.domain
    service: http://localhost:80
  - hostname: pi.your.domain
    service: ssh://localhost:22
  - hostname: dl.your.domain
    service: http://localhost:9091
  - hostname: medusa.your.domain
    service: http://localhost:8081
  - hostname: plex.your.domain
    service: http://localhost:32400
  - hostname: tau.your.domain
    service: http://localhost:8181
  - service: http_status:404
```
