### DISCUSSION TITLE
DietPi-Software | Paperless-ngx

### DISCUSSION THREAD

**Discussion by HyperCriSiS** [MichaIng/DietPi#5489] [Software Request]
Would be awesome to have this on DietPi.

Paperless-ngx is a document management system that transforms your physical documents into a searchable online archive so you can keep, well, less paper.
A demo is available at [demo.paperless-ngx.com](https://demo.paperless-ngx.com/) using login demo / demo. Note: demo content is reset frequently and confidential information should not be uploaded.

https://github.com/paperless-ngx/paperless-ngx

Installation:
https://docs.paperless-ngx.com/setup/#setup-bare-metal

or with docker:
https://docs.paperless-ngx.com/setup/#docker_script

If docker is chosen, it would be nice to have an easy way to save data outside the container.
(I hope you prefer bare metal installations. Docker is a true abomination.)

Vote for this software via up button at this post.

**Comment by HyperCriSiS** [comment]
It would be so awesome to have this on Dietpi. Is there any chance this will be in one of the next releases? :blush:

**Reply by MichaIng** [reply]
Not if no one else does a start with implementing this: https://github.com/MichaIng/DietPi/wiki/How-to-add-a-new-software-title

We have a veeery long list of software requests, some with a lot more traction, but I won't find time to implement any soon by myself, as there is a lot hardware/SBC/kernel work to do, which currently has higher priority for me.

**Reply by HyperCriSiS** [reply]
OK sad. I understand. Thought it has a chance because it is in the tops regarding votes. :)

**Reply by MichaIng** [reply]
Oh right, indeed highly voted. Then "some with a lot more traction" is not quite correct.

**Comment by HyperCriSiS** [comment]
New Update :smile:

paperless-ngx 2.9.0
Features

    Feature: Allow a data only export/import cycle @stumpylog (https://github.com/paperless-ngx/paperless-ngx/pull/6871)
    Change: rename 'redo OCR' to 'reprocess' to clarify behavior @shamoon (https://github.com/paperless-ngx/paperless-ngx/pull/6866)
    Enhancement: Support custom path for the classification file @lino-b (https://github.com/paperless-ngx/paperless-ngx/pull/6858)
    Enhancement: default to title/content search, allow choosing full search link from global search @shamoon (https://github.com/paperless-ngx/paperless-ngx/pull/6805)
    Enhancement: only include correspondent 'last_correspondence' if requested @shamoon (https://github.com/paperless-ngx/paperless-ngx/pull/6792)
    Enhancement: delete pages PDF action @shamoon (https://github.com/paperless-ngx/paperless-ngx/pull/6772)
    Enhancement: support custom logo / title on login page @shamoon (https://github.com/paperless-ngx/paperless-ngx/pull/6775)

Bug Fixes

    Fix: including ordering param for id__in retrievals @shamoon (https://github.com/paperless-ngx/paperless-ngx/pull/6875)
    Fix: Don't allow the workflow save to override other process updates @stumpylog (https://github.com/paperless-ngx/paperless-ngx/pull/6849)
    Fix: consistently use created_date for doc display @shamoon (https://github.com/paperless-ngx/paperless-ngx/pull/6758)

Maintenance

    Chore: Change the code formatter to Ruff @stumpylog (https://github.com/paperless-ngx/paperless-ngx/pull/6756)
    Chore: Backend updates @stumpylog (https://github.com/paperless-ngx/paperless-ngx/pull/6755)
    Chore(deps): Bump crowdin/github-action from 1 to 2 in the actions group https://github.com/dependabot (https://github.com/paperless-ngx/paperless-ngx/pull/6881)

**Comment by oldboys92** [comment]
I've added this very easy in Portainer using a `docker-compose.yml` from Paperless-ngx. It is running without problems on my 8Gb RPi4 inside Portainer. A little bit of effort is required to configure and you need to learn also a little bit Portainer, but it is doable.

here my docker-compose.yml

```yaml
# Docker Compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8010.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Open portainer Stacks list and click 'Add stack'
# - Paste the contents of this file and assign a name, e.g. 'paperless'
# - Click 'Deploy the stack' and wait for it to be deployed
# - Open the list of containers, select paperless_webserver_1
# - Click 'Console' and then 'Connect' to open the command line inside the container
# - Run 'python3 manage.py createsuperuser' to create a user
# - Exit the console
#
# For more extensive installation and update instructions, refer to the
# documentation.

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /mnt/dietpi_userdata/paperless/redis/data:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - /mnt/dietpi_userdata/paperless/pgsql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "127.0.0.1:8010:8000"
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:8000
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/dietpi_userdata/paperless/data:/usr/src/paperless/data
      - /mnt/dietpi_userdata/paperless/media:/usr/src/paperless/media
      - /mnt/dietpi_userdata/paperless/export:/usr/src/paperless/export
      - /mnt/dietpi_userdata/paperless/consume:/usr/src/paperless/consume
      - /mnt/dietpi_userdata/paperless/scripts:/usr/src/paperless/scripts
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    env_file:
      - docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
```

end my docker-compose.env

```bash
USERMAP_UID: ${USERMAP_UID}
USERMAP_GID: ${USERMAP_GID}

PAPERLESS_URL: ${PAPERLESS_URL}
PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
PAPERLESS_TIME_ZONE: ${PAPERLESS_TIME_ZONE}
PAPERLESS_OCR_LANGUAGE: ${PAPERLESS_OCR_LANGUAGE}
PAPERLESS_OCR_PAGES: ${PAPERLESS_OCR_PAGES}

# settings for adapting the RPI performance
PAPERLESS_TASK_WORKERS: ${PAPERLESS_TASK_WORKERS}
PAPERLESS_THREADS_PER_WORKER: ${PAPERLESS_THREADS_PER_WORKER}
PAPERLESS_OCR_CLEAN: ${PAPERLESS_OCR_CLEAN}
PAPERLESS_WEBSERVER_WORKERS: ${PAPERLESS_WEBSERVER_WORKERS}

PAPERLESS_ENABLE_NLTK: ${PAPERLESS_ENABLE_NLTK}

# Admin account credentials
PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER}
PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_ADMIN_PASSWORD}
PAPERLESS_APPS: ${PAPERLESS_APPS}

# social account provider for OIDC Oauth
PAPERLESS_SOCIALACCOUNT_PROVIDERS: ${PAPERLESS_SOCIALACCOUNT_PROVIDERS}

# preconsume script for removing blank pages (/usr/src/paperless/scripts/remove-blank-pages.sh)
PAPERLESS_PRE_CONSUME_SCRIPT: ${PAPERLESS_PRE_CONSUME_SCRIPT}

# barcode and qr code support for ASN based workflow
PAPERLESS_CONSUMER_ENABLE_BARCODES: ${PAPERLESS_CONSUMER_ENABLE_BARCODES}
PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: ${PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE}
```
