### DISCUSSION TITLE
Software request Stirling PDF

### DISCUSSION THREAD

**Discussion by Frooodle** [MichaIng/DietPi#6839] [Software Request]
Software request for Stirling PDF 

https://github.com/Stirling-Tools/Stirling-PDF

Local version guide has many dependencies 
https://github.com/Stirling-Tools/Stirling-PDF/blob/main/LocalRunGuide.md

Step 2 can be ignored in guide and step 4 could instead download jar from release artifacts

**Comment by mews-se** [comment]
I run it as a docker container btw! Works fine

```
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8083:8080'   # change the left side port if 8080 is already in use on your host machine
    volumes:
      - ./trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    restart: unless-stopped
```
