### ISSUE TITLE
DietPi-Software | NGINX Proxy Manager (NPM)

### ISSUE THREAD

**Issue by LilTrublMakr** [MichaIng/DietPi#4417]
Sorry if this has been suggested before. I did search for `npm` and `nginx proxy manager` but did not see an issue for it.

#### Formal software information
- Software title | NGINX Proxy Manager (NPM)
- Short description | Reverse proxy manager, certificate manager
- Official URL (if available) | https://nginxproxymanager.com/
- GitHub URL (if available) | https://github.com/jc21/nginx-proxy-manager
- (Official) install documentation | https://nginxproxymanager.com/setup/

#### Are there similar/alternative software titles available with DietPi-Software?
NGINX (with a lot of manual setup)

#### What makes your requested software better than the above solutions, if available?
NPM provides a GUI that lets users make a simple reverse proxy, manage certificates, and much more. It is simple for newer people but allows you to get complicated as well.

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?
Though NPM is available for Docker only, it does allow the use of a SQLite database to keep everything self contained.

#### Can you provide the installation steps that you would suggest DietPi-Software to do?
1. Prerequisites: docker, docker-compose
2. Take the compose file from the installation documentation and modify it to use SQLite rather than a MySQL database.
3. Manually create the SQLite database file.*
4. Run docker-compose.

*One problem I did run in to is that I had to manually create the `database.sqlite` file by running a touch command because docker-compose was creating it as a directory rather than a file. It was starting the container but was throwing a `Bad gateway` error when trying to log in for the first time.

My example compose file:
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? 
I can attempt to do the legwork of getting it added as an option, but support will be tough.

#### Vote for this software on FeatHub: https://feathub.com/MichaIng/DietPi/+101

**Comment by Joulinar** [comment]
Hi,

I don't think this will be implemented as it's a simple docker container that can be installed via docker-compose. Both docker and docker-compose are available via DietPi software catalogue

**Comment by LilTrublMakr** [comment]
I guess Portainer is more advanced to set up? It it not a "simple docker container" as well?

With NPM being one of the top 15 requests on FeatHub, I think it is something that should be considered as an exception to the 'no Docker containers' train of thought. Clearly, the want is there, and there is now a solution to keeping it self contained by using SQLite instead of having the hassle of goin through an external DB or starting a new DB with Docker. A lot of people struggle with reverse proxys and this is a really nice GUI solution that novices and pros alike can use.

**Comment by Joulinar** [comment]
Portainer is offered as management tool for Docker 

For revers proxy, we are looking into `frp` at the moment https://github.com/MichaIng/DietPi/issues/4395

**Comment by LilTrublMakr** [comment]
That looks very overly complicated to use. I have been looking at that for 5 mins and I have no clue what is going on besides looking like there are a ton of config files to edit. The GUI part looks to just be an information page with pretty graphs and numbers, nothing actually functional. Some people will like that, but I feel that it is not very novice friendly. 

I hope more people will chime in and show interest for an official implementation. But for those that would like to run NPM without using an external database, here is how I got it to work:

1. Open a SSH terminal and navigate to where you keep your Docker container data. I create a subfolder for each of my containers so `./npm/` will be the file my docker-compose file will be in.
2. Create your `docker-compose.yml` file with the following content:
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:2'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
Modify as needed.

3. We need to create a database before starting the container since the docker container does not seem to create it. If we don't do this, you will get a `Bad gateway` error when logging in for the first time. Run this command: `touch ./data/database.sqlite`.
4. Start your container with the following command: `docker-compose up -d`.
5. When that is complete, you should be able to access NPM through your browser using `http://dietpi:81` or `<ip of DietPi>:81`. The default log in credentials are UN `admin@example.com` and PW `changeme`.

I hope someone finds this helpful.
