### ISSUE TITLE
Unifi with Docker - strange Memory Consumption

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#5056]
<div type='discussions-op-text'>

<sup>Originally posted by **Gill-Bates** December  9, 2021</sup>
Hey there,

the Unifi products are very popular as far as I know and the Unifi controller also ran natively on the Dietpi until Debian Stretch. Since Buster there is the problem with MongoDB. Therefore, Docker is the only solution if you want to use a current OS, but still do not want to do without the Unifi controller.

If I install the 64-bit operating system from Dietpi, my RAM is almost at the limit:

![image](https://user-images.githubusercontent.com/25774289/145446354-4d741d88-3da3-4c7a-8aee-a7991ce9ee7d.png)

But here's the crazy thing: if I use the 32-bit version, the container makes do with half the memory:

![image](https://user-images.githubusercontent.com/25774289/145446534-b58e481d-0b35-40a3-851c-80ed59db7b85.png)

Mind you, my `docker-compose.yml` is identical in both cases!

```
---
version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=512M #optional
      - MEM_STARTUP=256M #optional
    volumes:
      - data:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: always
volumes:
 data:
```
